
services:

  mariadb:
    image: mariadb:11.4.2-noble
    container_name: recordings-db
    volumes:
      - /srv/mariadb:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3326:3306"
    environment:
      TZ: America/New_York
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  adminer:
    image: adminer
    container_name: recordings-adminer
    ports:
      - "8280:8080"
    environment:
      ADMINER_DESIGN: flat
